[package]
name = "simgame_util"
version = "0.1.0"
authors = ["Bradley Hardy"]
edition = "2018"

[dependencies]
cgmath = { version = "0.18", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
rand = "0.7"
log = "0.4"
byteorder = "1.3"
crossbeam = "0.7"
