[package]
name = "simgame_shaders"
version = "0.1.0"
authors = ["Bradley Hardy <bradleyhardy@live.com>"]
edition = "2018"

[features]
shader-compiler = ["shaderc"]

[dependencies]
shaderc = { version = "*", optional = true }
anyhow = "*"
log = "*"
