[package]
name = "simgame_render"
version = "0.1.0"
authors = ["Bradley Hardy"]
edition = "2018"

[dependencies]
simgame_core = { path = "../core" }
cgmath = "0.17"
directories = "2.0"
anyhow = "1.0"
log = "0.4"
# graphics
winit = "0.20.0-alpha4"
raw-window-handle = "0.3"
wgpu = "0.4"
zerocopy = "*"
rand = "0.7.3"
