[package]
name = "simgame_render"
version = "0.1.0"
authors = ["Bradley Hardy"]
edition = "2018"

[dependencies]
simgame_core = { path = "../core" }
cgmath = "*"
directories = "*"
anyhow = "*"
log = "*"
# graphics
winit = "*"
raw-window-handle = "*"
wgpu = "*"
zerocopy = "*"
rand = "*"
smol = "*"
