[package]
name = "simgame"
version = "0.1.0"
authors = ["Bradley Hardy <bradleyhardy@live.com>"]
edition = "2018"

[features]
shader-compiler = ["simgame_shaders/shader-compiler"]

[dependencies]
simgame_core = { path = "../core/" }
simgame_render = { path = "../render/" }
simgame_shaders = { path = "../shaders/" }
simgame_worldgen = { path = "../worldgen/" }
cgmath = "*"
structopt = "*"
env_logger = "*"
log = "*"
anyhow = "*"
smol = "*"
winit = "*"
rand = "*"
serde_yaml = "*"
