[package]
name = "simgame"
version = "0.1.0"
authors = ["Bradley Hardy <bradleyhardy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simgame_core = { path = "../core/" }
simgame_render = { path = "../render/" }
simgame_shaders = { path = "../shaders/" }
cgmath = "*"
structopt = "*"
env_logger = "*"
log = "*"
anyhow = "*"
